### ISSUE TITLE
Bug with synchronized lock on Main.pendingPullingTable object 

### ISSUE THREAD

**Issue by geektortoise** [Cytomine-ULiege/Cytomine-software-router#6]
If I add a software then try to run it before the image was pulled by the ImagePullerThread, I have an infinite loop with the message "The image [X] is currently being pulled ! Wait..."

Even when the image is pulled and moved, it is not removed from the pendingPullingTable collection.
https://github.com/Cytomine-ULiege/Cytomine-software-router/blob/master/src/main/groovy/be/cytomine/software/repository/threads/ImagePullerThread.groovy#L54

The origin is from the synchronized keyword into the ProcessingServerThread that "lock" the collection.
https://github.com/Cytomine-ULiege/Cytomine-software-router/blob/master/src/main/groovy/be/cytomine/software/consumer/threads/ProcessingServerThread.groovy#L102

Removing the 
`synchronized (Main.pendingPullingTable)` 
from the ProcessingServerThread resolves this issue.

However, I'm wondering why there is a "synchronized" at this line.
The only use of pendingPullingTable is at the while that represent "as long as my collection doesn't change, loop" ... but the possible changes by other thread are locked.

Also, if we enter into the while and, at the second after, the imageName are no more into the collection, it will not be a big problem, we will just wait 1 more minute.

Am I missing a point here ?

**Comment by geektortoise** [comment]
NB : this is still present in your other branch into the RabbitMQProcessing class :-)

**Comment by urubens** [comment]
Yes, you're right. I don't think you're missing a point. As far as I remember, it don't see any reason for the `synchronized` keyword here. Maybe an heritage of an old refactoring ? 

Anyway, it will be a boring bug solved ! :)
